### ISSUE TITLE
json conversion

### ISSUE THREAD

**Issue by vczulak** [feltron/MMapper#11]
Hi,
I have been using mmapper for close to a month and am loving almost all of it. I am using the program towards a graduate landscape architecture project at the University of Pennsylvania. I am trying to export the geo data from from mmapper into Rhino and Grasshopper. Where I am having a problem is the .json files. Extracting the data out of them and into Grasshopper is proving very challenging. I am able to get .gpx files in rather easily, is their a way to convert the mmapper .json into a .gpx?

Thanks for any help!

**Comment by feltron** [comment]
Glad that you're enjoying the app… unfortunately, exporting .gpx files is not within the scope of this application. If you are interested in tools for extracting your Moves App data, you may find something more effective here:

https://apps.moves-app.com
