### ISSUE TITLE
App show statistics only about current day

### ISSUE THREAD

**Issue by tamvodopad** [feltron/MMapper#29]
In last processing 2.2.1 app showing statistics only about last day.
https://www.dropbox.com/s/i60v3bdk9owwyg0/error_movesmapper.png
and i can not view all gui elements, app have only day slider.

**Comment by feltron** [comment]
I think that your sketch is too large for the resolution of your screen. If you boost the resolution or make the sketch smaller, you should see the rest of the controls.
