### ISSUE TITLE
Incorrect Date when Querying API

### ISSUE THREAD

**Issue by MattyBearBytes** [feltron/MMapper#4]
It appears that the jsonDate that is being crafted to use in the API calls isn't padding the month correctly.

Eg,
Querying... 2013902

This should be "20130902"

**Comment by chadvavra** [comment]
see https://github.com/feltron/MMapper/issues/5

**Comment by feltron** [comment]
Fixed: https://github.com/feltron/MMapper/commit/77284be2e85e99a119b31111e55ec8044970b03d
