### ISSUE TITLE
can't get any data, 

### ISSUE THREAD

**Issue by oatcracker** [feltron/MMapper#5]
Hi, Nicholas,

I got the following error after i put in the long token string obtained from Moves website:

Querying… 2013904
java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.moves-app.com/api/v1/user/storyline/daily/2013904?trackPoints=true&access_token=(... the long token string ...)

Advices are appreciated!

Thanks!
- J

**Comment by oatcracker** [comment]
seems the following code doesn't work :

```
  if (d1.getValue() < 9) {
    month = "0" + str(int(d1.getValue()));
  } 
  else {
    month = str(int(d1.getValue()));
  }
```

**Comment by oatcracker** [comment]
sorry, I accidentally closed this issue, it's not solved yet ...

**Comment by chadvavra** [comment]
change "2013904"
to "20130904"

**Comment by oatcracker** [comment]
Thanks! But how? The value of moveDate is affected by the GUI for year, month, and day ...

**Comment by chadvavra** [comment]
so, in the 'functions' file, change 

**crib notes - change the "9"s to "10"s**

void listDates() {
  movesDates = new int[0];
  for (int i=0; i<checkbox.getArrayValue().length; i++) {
    if (checkbox.getArrayValue(i) != 0) {
      if (d1.getValue() < 9) {
        month = "0" + str(int(d1.getValue()));
      } 
      else {
        month = str(int(d1.getValue()));
      }
      if (i < 9) {
        day = "0" + str(i+1);
      } 
      else {
        day = str(i+1);
      }
      year = str(int(d2.getValue()));
      date = year + month + day;
      movesDates = append(movesDates, int(date));
    }
  }

to:

void listDates() {
  movesDates = new int[0];
  for (int i=0; i<checkbox.getArrayValue().length; i++) {
    if (checkbox.getArrayValue(i) != 0) {
      if (d1.getValue() < 10) {
        month = "0" + str(int(d1.getValue()));
      } 
      else {
        month = str(int(d1.getValue()));
      }
      if (i < 10) {
        day = "0" + str(i+1);
      } 
      else {
        day = str(i+1);
      }
      year = str(int(d2.getValue()));
      date = year + month + day;
      movesDates = append(movesDates, int(date));
    }
  }

**Comment by oatcracker** [comment]
oh, how dumb am I ! Thanks, Chad!

new error for "max_lats.set(jsonDate, max(path_lat));" part of the code:
ArrayIndexOutOfBoundsException: Cannot use min() or max() on an empty array. 

Is it because I don't have any data for the current day? (my phone is on the table since 11pm ...)

**Comment by feltron** [comment]
Yep… that's this issue: https://github.com/feltron/MMapper/issues/1

**Comment by oatcracker** [comment]
I think this change about "checkbox.toggle(day_-1);" may work:

change:

// Populate Days Dropdown 
// - - - - - - - - - - - - - - - - - - - - - - - 
void GUIday(int year_, int month_, int day_) {
  if (month_ == month() && year_ == year()) {
    for (int i=1; i<=day(); i++) {
      checkbox.addItem(str(i), i);
    }
    checkbox.toggle(day_-1);
  } 

to

// Populate Days Dropdown 
// - - - - - - - - - - - - - - - - - - - - - - - 
void GUIday(int year_, int month_, int day_) {
  if (month_ == month() && year_ == year()) {
    for (int i=1; i<=day(); i++) {
      checkbox.addItem(str(i), i);
    }
    checkbox.toggle(day_-2);
  } 

So by default the program will always initialize with the data of the day before the current day. Correct me if I'm wrong ...

**Comment by feltron** [comment]
My plan is to add some error protection so that the app won't crash if there isn't data to return for the current day or if there is only 1 location.
