### ISSUE TITLE
Error when selecting the 10th day of the month

### ISSUE THREAD

**Issue by ctaloi** [feltron/MMapper#8]
Received an error when selecting the 10th day of the month (month 8 in the example).  The moves API returns an "invalid time"

```
 {"error":"invalid time format: 201308010"}
```

It looks like a 0 is appended before the 10 in the call

```
 https://api.moves-app.com/api/v1/user/storyline/daily/201308010
```

I looked for where the error might be, but am not very Java literate

I added a print to jsonFetch(String fetchDate)

```
 println("--FetchDate: " + fetchDate);
```

and the console prints

```
 --FetchDate: 20130809
 - - - - - - - - - - - - - - -
 --FetchDate: 201308010
 Querying… 201308010
 java.io.IOException: Server returned HTTP response code: 400
```

Selecting the 11th day of the month seems fine, which seems strange - the references to format your date read correct (if <= 9)

Sorry I couldn't find the bug !!

**Comment by chadvavra** [comment]
I suspect it is in the same listDates() function.

  if (i <= 9) {
        day = "0" + str(i+1);

This would suggest that if i = 9, day = 010.
I don't have data for last month so I can't debug it.

sorry.

**Comment by chadvavra** [comment]
try changing it to:

if (i < 9) {
day = "0" + str(i+1)

**Comment by ctaloi** [comment]
That did it !
